volumes:
    laravel:

services:
  laravel:
    image: senither/custodian-php-laravel-livewire:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: custodian-laravel-livewire
    ports:
      - 8000:80
    volumes:
      - laravel:/var/www/html/storage
