name: GO + Fiber + HTMX

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - 'go-fiber-htmx/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    name: Test

    defaults:
      run:
        working-directory: go-fiber-htmx

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./...
